### PR TITLE
Added note listing UI

### PR DESCRIPTION
**Pull request by aagneyanNamboodiri**
Added the components for listing the notes in dashboard.

### CODE REVIEW

**Comment by yedhink** [comment]
@aagneyanNamboodiri I have provided some reviews for the other PR that you had merged. Go through it and fix the issues mentioned in this PR itself.

**Comment by yedhink** [comment]
@aagneyanNamboodiri https://www.loom.com/share/b0fb5788fdd346ac8a082dbc33e2c36a

**Comment by aagneyanNamboodiri** [comment]
@yedhink https://www.loom.com/share/03d3b840e163476ea570fb3d3f908238

I am working on the issues right now

**Comment by yedhink** [comment]
@aagneyanNamboodiri Understood. Thanks for the video. Appreciate it.

**Pull request merged**
